mcdc_coverage_gen.py: skip expression with wrong tracepoint
In case if there were issues with expression to tracepoints
mapping the following exception may occurr:

Traceback (most recent call last):
  File "./mcdc-tool/mcdc_coverage_gen.py", line 456, in <module>
    main()
  File "./mcdc-tool/mcdc_coverage_gen.py", line 451, in main
    coverage_data = process_mcdc_coverage(merged_trace_data, dwarf_map)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./mcdc-tool/mcdc_coverage_gen.py", line 297, in process_mcdc_coverage
    test_vectors = _evaluate_test_vectors(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "./mcdc-tool/mcdc_coverage_gen.py", line 181, in _evaluate_test_vectors
    leaf = leafs[leaf_idx]
           ~~~~~^^^^^^^^^^
IndexError: list index out of range

Thus skip calculation of such expressoins for now.

Signed-off-by: Ruslan Ruslichenko <Ruslan_Ruslichenko@epam.com>